#!/bin/bash

. `dirname "$0"`/active_databases

DATE=`date -I`

for i in $ACTIVE_DATABASES
do
    echo "Saving edits of $i ..."
    python3 -m scripts.cceh.save_edits -vvv -o - "instance/$i.conf" | gzip > "backups/saved_edits_${i}_${DATE}.xml.gz"
done
